export const SCREENS = {
  HOME: "HOME",
  LOGIN: "LOGIN",
  COORDINATION_DETAIL: "COORDINATION_DETAIL",
  PROFILE: "PROFILE",
  TRIP_STATUSES: "TRIP_STATUSES",

  // stack
  MAIN_BOTTOM_TAB: "MAIN_BOTTOM_TAB",
};
